// taskflow-app-main/src/components/Tasks/TaskModal.tsx
import { useState, useEffect } from 'react';
import { X } from 'lucide-react';
import { Task } from '../../types/database';
import { Category } from '../../services/categoryService';
import AISuggestions from './AISuggestions';
import { TaskDetails } from './TaskDetails';

interface TaskModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSave: (task: { 
    title: string; 
    description?: string; 
    completed?: boolean;
    category?: string;
    tags?: string[];
    due_date?: string;
    priority?: 'low' | 'medium' | 'high';
  }) => void;
  editingTask?: Task | null;
  categories?: Category[];
  selectedDate?: Date | null;
}

const TaskModal: React.FC<TaskModalProps> = ({ isOpen, onClose, onSave, editingTask, categories = [], selectedDate }) => {
  const [formData, setFormData] = useState({
    title: '',
    description: '',
    completed: false,
    category: '',
    tags: [] as string[],
    due_date: '',
    priority: '' as '' | 'low' | 'medium' | 'high'
  });
  
  const [tagInput, setTagInput] = useState('');

  // Resetear formulario cuando el modal se abre/cierra o cambia la tarea editada
  useEffect(() => {
    if (isOpen) {
      // Prevenir scroll del body cuando el modal está abierto
      document.body.style.overflow = 'hidden';
      
      if (editingTask) {
        // Convert tags from string to array if needed
        let taskTags: string[] = [];
        if (editingTask.tags) {
          if (Array.isArray(editingTask.tags)) {
            taskTags = editingTask.tags;
          } else if (typeof editingTask.tags === 'string') {
            taskTags = editingTask.tags.split(',').filter(t => t.trim());
          }
        }
        
        setFormData({
          title: editingTask.title,
          description: editingTask.description || '',
          completed: editingTask.completed,
          category: editingTask.category || '',
          tags: taskTags,
          due_date: editingTask.due_date ? editingTask.due_date.split('T')[0] : '',
          priority: editingTask.priority || ''
        });
      } else {
        // Cuando se crea una nueva tarea, usar selectedDate si está disponible
        const initialDueDate = selectedDate 
          ? selectedDate.toISOString().split('T')[0] 
          : '';
        setFormData({
          title: '',
          description: '',
          completed: false,
          category: '',
          tags: [],
          due_date: initialDueDate,
          priority: ''
        });
      }
      setTagInput('');
    } else {
      // Restaurar scroll del body cuando el modal se cierra
      document.body.style.overflow = 'auto';
    }

    // Cleanup function para restaurar scroll cuando el componente se desmonta
    return () => {
      document.body.style.overflow = 'auto';
    };
  }, [isOpen, editingTask, selectedDate]);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!formData.title.trim()) return;
    
    const submitData = {
      ...formData,
      priority: formData.priority || undefined,
      due_date: formData.due_date || undefined,
      category: formData.category || undefined,
      tags: formData.tags.length > 0 ? formData.tags.join(',') : undefined
    };
    
    onSave(submitData);
    onClose();
  };

  const handleAddTag = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Enter' && tagInput.trim()) {
      e.preventDefault();
      if (!formData.tags.includes(tagInput.trim())) {
        setFormData(prev => ({
          ...prev,
          tags: [...prev.tags, tagInput.trim()]
        }));
      }
      setTagInput('');
    }
  };

  const handleAISuggestion = (type: 'category' | 'due_date' | 'priority', value: any) => {
    switch (type) {
      case 'category':
        setFormData(prev => ({ ...prev, category: value }));
        break;
      case 'due_date':
        setFormData(prev => ({ ...prev, due_date: value }));
        break;
      case 'priority':
        setFormData(prev => ({ ...prev, priority: value }));
        break;
    }
  };

  const handleRemoveTag = (tagToRemove: string) => {
    setFormData(prev => ({
      ...prev,
      tags: prev.tags.filter(tag => tag !== tagToRemove)
    }));
  };

  if (!isOpen) return null;

  return (
    <div 
      className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4 z-50"
      onWheel={(e) => e.stopPropagation()}
    >
      <div 
        className="bg-white dark:bg-gray-800 rounded-lg max-w-md w-full max-h-[60vh] min-h-[400px] flex flex-col"
        onWheel={(e) => e.stopPropagation()}
      >
        <div className="flex items-center justify-between p-4 md:p-6 border-b dark:border-gray-700 flex-shrink-0">
          <h2 className="text-lg md:text-xl font-semibold text-gray-900 dark:text-white">
            {editingTask ? 'Editar tarea' : 'Nueva tarea'}
          </h2>
          <button
            onClick={onClose}
            className="text-gray-400 dark:text-gray-500 hover:text-gray-600 dark:hover:text-gray-300 transition-colors"
          >
            <X className="h-6 w-6" />
          </button>
        </div>

        <div 
          className="flex-1 overflow-y-scroll min-h-0 modal-scroll" 
          style={{ 
            maxHeight: 'calc(60vh - 160px)' // Resta el header y footer
          }}
          onWheel={(e) => e.stopPropagation()}
        >
          <form id="task-form" onSubmit={handleSubmit} className="p-4 md:p-6 space-y-4">
          <div>
            <label htmlFor="title" className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              Título *
            </label>
            <input
              type="text"
              id="title"
              name="title"
              required
              value={formData.title}
              onChange={(e) => setFormData(prev => ({ ...prev, title: e.target.value }))}
              className="w-full px-3 py-2 border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-700 text-gray-900 dark:text-white rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500 text-sm md:text-base"
              placeholder="¿Qué necesitas hacer?"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              Descripción
            </label>
            <textarea
              value={formData.description}
              onChange={(e) => setFormData(prev => ({ ...prev, description: e.target.value }))}
              className="w-full border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-700 text-gray-900 dark:text-white rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
              rows={3}
              placeholder="Descripción de la tarea..."
            />
          </div>

          {/* Category */}
          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              Categoría
            </label>
            <select
              value={formData.category || ''}
              onChange={(e) => setFormData(prev => ({ ...prev, category: e.target.value }))}
              className="w-full border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-700 text-gray-900 dark:text-white rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
            >
              <option value="">Seleccionar categoría...</option>
              {categories.map((category) => (
                <option key={category.id} value={category.name}>
                  {category.name}
                </option>
              ))}
            </select>
          </div>

          {/* Tags */}
          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              Etiquetas
            </label>
            <div className="space-y-2">
              <input
                type="text"
                value={tagInput}
                onChange={(e) => setTagInput(e.target.value)}
                onKeyDown={handleAddTag}
                className="w-full border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-700 text-gray-900 dark:text-white rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
                placeholder="Presiona Enter para agregar etiqueta..."
              />
              {formData.tags.length > 0 && (
                <div className="flex flex-wrap gap-2 max-h-20 overflow-y-auto">
                  {formData.tags.map((tag, index) => (
                    <span
                      key={index}
                      className="bg-blue-100 dark:bg-blue-900 text-blue-800 dark:text-blue-200 px-2 py-1 rounded-full text-sm flex items-center gap-1"
                    >
                      {tag}
                      <button
                        type="button"
                        onClick={() => handleRemoveTag(tag)}
                        className="text-blue-600 dark:text-blue-400 hover:text-blue-800 dark:hover:text-blue-200"
                      >
                        <X className="w-3 h-3" />
                      </button>
                    </span>
                  ))}
                </div>
              )}
            </div>
          </div>

          {/* Due Date */}
          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              Fecha de vencimiento
            </label>
            <input
              type="date"
              value={formData.due_date || ''}
              onChange={(e) => setFormData(prev => ({ ...prev, due_date: e.target.value }))}
              className="w-full border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-700 text-gray-900 dark:text-white rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
            />
          </div>

          {/* Priority */}
          <div>
            <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              Prioridad
            </label>
            <select
              value={formData.priority || ''}
              onChange={(e) => setFormData(prev => ({ ...prev, priority: e.target.value as 'low' | 'medium' | 'high' | '' }))}
              className="w-full border border-gray-300 dark:border-gray-600 bg-white dark:bg-gray-700 text-gray-900 dark:text-white rounded-lg px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
            >
              <option value="">Seleccionar prioridad...</option>
              <option value="low">Baja</option>
              <option value="medium">Media</option>
              <option value="high">Alta</option>
            </select>
          </div>

          {/* Sugerencias de IA */}
          <AISuggestions
            title={formData.title}
            description={formData.description}
            onSuggestionAccept={handleAISuggestion}
          />

            {/* Task Details - Solo mostrar si estamos editando una tarea existente */}
            {editingTask && editingTask.id && (
              <div className="mt-6">
                <TaskDetails task={editingTask} />
              </div>
            )}
            </form>
        </div>

        {/* Botones fijos en la parte inferior */}
        <div className="flex justify-end space-x-3 p-4 md:p-6 border-t dark:border-gray-700 flex-shrink-0">
          <button
            type="button"
            onClick={onClose}
            className="px-4 py-2 text-sm font-medium text-gray-700 dark:text-gray-300 bg-gray-100 dark:bg-gray-700 hover:bg-gray-200 dark:hover:bg-gray-600 rounded-lg transition-colors"
          >
            Cancelar
          </button>
          <button
            type="submit"
            form="task-form"
            className="px-4 py-2 text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 rounded-lg transition-colors"
          >
            {editingTask ? 'Actualizar' : 'Crear tarea'}
          </button>
        </div>
      </div>
    </div>
  );
};

export default TaskModal;

// taskflow-app-vue/src/components/TaskModal.vue
<script setup lang="ts">
import { ref, watch, computed } from 'vue';
import type { Task, Category } from '@/types';
import {
  X, Flag, FileText, Target, AlertTriangle, CheckCircle,
  Plus, Hash, Paperclip, MessageSquare, Clock, Trash2, Calendar,
  Sparkles, Send
} from 'lucide-vue-next';

const props = withDefaults(defineProps<{
  isOpen: boolean;
  task: Task | null;
  categories?: Category[];
}>(), {
  categories: () => []
});

const emit = defineEmits(['close', 'save']);

const taskCategories = [
  { name: 'Trabajo', icon: '💼' },
  { name: 'Personal', icon: '🏠' },
  { name: 'Estudio', icon: '📚' },
  { name: 'Salud', icon: '⚕️' },
  { name: 'Compras', icon: '🛒' },
  { name: 'Viajes', icon: '✈️' },
];

const activeTab = ref<'details' | 'attachments' | 'activity'>('details');

const form = ref({
  title: '',
  description: '',
  priority: 'medium' as 'low' | 'medium' | 'high',
  dueDate: '',
  category: '',
  tags: [] as string[]
});

const newTag = ref('');

const activity = ref<{ id: string; action: string; details: string; created_at: string; user_name: string }[]>([]);

watch(() => props.task, (newTask) => {
  if (newTask) {
    let taskTags: string[] = [];
    if (newTask.tags) {
      if (Array.isArray(newTask.tags)) {
        taskTags = newTask.tags;
      } else if (typeof newTask.tags === 'string') {
        taskTags = newTask.tags.split(',').filter((t: string) => t.trim());
      }
    }

    form.value = {
      title: newTask.title,
      description: newTask.description || '',
      priority: newTask.priority || 'medium',
      dueDate: newTask.dueDate || '',
      category: newTask.categoryId?.toString() || '',
      tags: taskTags
    };
    addActivity('Tarea abierta', `Se abrió la tarea "${newTask.title}"`);
  } else {
    resetForm();
  }
}, { immediate: true });

function resetForm() {
  form.value = {
    title: '',
    description: '',
    priority: 'medium',
    dueDate: '',
    category: '',
    tags: []
  };
  activity.value = [];
}

function addTag() {
  if (newTag.value.trim() && !form.value.tags.includes(newTag.value.trim())) {
    form.value.tags = [...form.value.tags, newTag.value.trim()];
    newTag.value = '';
  }
}

function removeTag(tagToRemove: string) {
  form.value.tags = form.value.tags.filter(tag => tag !== tagToRemove);
}

function addActivity(action: string, details: string) {
  activity.value.unshift({
    id: Date.now().toString(),
    action,
    details,
    created_at: new Date().toISOString(),
    user_name: 'Tú'
  });
}

function handleSubmit() {
  if (!form.value.title.trim()) return;

  const taskData = {
    title: form.value.title,
    description: form.value.description,
    priority: form.value.priority,
    dueDate: form.value.dueDate,
    categoryId: form.value.category ? parseInt(form.value.category) : undefined,
    tags: form.value.tags
  };

  addActivity(props.task ? 'Tarea actualizada' : 'Tarea creada',
    props.task ? `Se actualizó la tarea "${form.value.title}"` : `Se creó la tarea "${form.value.title}"`);

  emit('save', taskData);
}

function formatDate(dateString: string) {
  const date = new Date(dateString);
  return date.toLocaleDateString('es-ES', {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });
}
</script>

<template>
  <div v-if="isOpen" class="fixed inset-0 z-50 flex items-center justify-center p-4">
    <div class="absolute inset-0 bg-black/50" @click="emit('close')"></div>

    <div class="relative bg-white dark:bg-gray-800 rounded-2xl shadow-2xl w-full max-w-2xl max-h-[90vh] overflow-hidden">
      <!-- Header -->
      <div class="flex items-center justify-between p-6 border-b border-gray-200 dark:border-gray-700">
        <div class="flex items-center space-x-3">
          <div class="w-10 h-10 bg-gradient-to-br from-blue-500 to-purple-500 rounded-xl flex items-center justify-center">
            <Target class="h-6 w-6 text-white" />
          </div>
          <div>
            <h2 class="text-xl font-bold text-gray-900 dark:text-white">
              {{ task ? 'Editar Tarea' : 'Nueva Tarea' }}
            </h2>
            <p class="text-sm text-gray-500 dark:text-gray-400">
              {{ task ? 'Actualiza los detalles de la tarea' : 'Crea una nueva tarea' }}
            </p>
          </div>
        </div>
        <button @click="emit('close')" class="p-2 text-gray-400 hover:text-gray-600 dark:hover:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 rounded-xl transition-all">
          <X class="h-5 w-5" />
        </button>
      </div>

      <!-- Tabs -->
      <div class="flex space-x-1 px-6 py-3 border-b border-gray-200 dark:border-gray-700">
        <button
          @click="activeTab = 'details'"
          :class="[
            'px-4 py-2 rounded-xl font-medium text-sm transition-all',
            activeTab === 'details'
              ? 'bg-gradient-to-r from-blue-600 to-purple-600 text-white'
              : 'text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700'
          ]"
        >
          <FileText class="h-4 w-4 inline mr-2" />
          Detalles
        </button>
        <button
          @click="activeTab = 'attachments'"
          :class="[
            'px-4 py-2 rounded-xl font-medium text-sm transition-all',
            activeTab === 'attachments'
              ? 'bg-gradient-to-r from-blue-600 to-purple-600 text-white'
              : 'text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700'
          ]"
        >
          <Paperclip class="h-4 w-4 inline mr-2" />
          Adjuntos
        </button>
        <button
          @click="activeTab = 'activity'"
          :class="[
            'px-4 py-2 rounded-xl font-medium text-sm transition-all',
            activeTab === 'activity'
              ? 'bg-gradient-to-r from-blue-600 to-purple-600 text-white'
              : 'text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700'
          ]"
        >
          <MessageSquare class="h-4 w-4 inline mr-2" />
          Actividad
        </button>
      </div>

      <!-- Content -->
      <div class="p-6 max-h-[60vh] overflow-y-auto">
        <!-- Details Tab -->
        <div v-if="activeTab === 'details'" class="space-y-6">
          <div>
            <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              Título *
            </label>
            <input
              v-model="form.title"
              type="text"
              required
              class="w-full px-4 py-3 bg-gray-100 dark:bg-gray-700 border border-transparent rounded-xl text-gray-900 dark:text-white placeholder-gray-500 dark:placeholder-gray-400 focus:bg-white dark:focus:bg-gray-600 focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20 transition-all duration-200"
              placeholder="Título de la tarea"
            />
          </div>

          <div>
            <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              Descripción
            </label>
            <textarea
              v-model="form.description"
              rows="4"
              class="w-full px-4 py-3 bg-gray-100 dark:bg-gray-700 border border-transparent rounded-xl text-gray-900 dark:text-white placeholder-gray-500 dark:placeholder-gray-400 focus:bg-white dark:focus:bg-gray-600 focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20 transition-all duration-200"
              placeholder="Descripción opcional de la tarea"
            ></textarea>
          </div>

          <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
            <div>
              <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                <Flag class="h-4 w-4 inline mr-1" />
                Prioridad
              </label>
              <select
                v-model="form.priority"
                class="w-full px-4 py-3 bg-gray-100 dark:bg-gray-700 border border-transparent rounded-xl text-gray-900 dark:text-white focus:bg-white dark:focus:bg-gray-600 focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20 transition-all duration-200"
              >
                <option value="low">Baja</option>
                <option value="medium">Media</option>
                <option value="high">Alta</option>
              </select>
            </div>

            <div>
              <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                <Calendar class="h-4 w-4 inline mr-1" />
                Fecha Límite
              </label>
              <input
                v-model="form.dueDate"
                type="date"
                class="w-full px-4 py-3 bg-gray-100 dark:bg-gray-700 border border-transparent rounded-xl text-gray-900 dark:text-white focus:bg-white dark:focus:bg-gray-600 focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20 transition-all duration-200"
              />
            </div>
          </div>

          <div>
            <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              Categoría
            </label>
            <select
              v-model="form.category"
              class="w-full px-4 py-3 bg-gray-100 dark:bg-gray-700 border border-transparent rounded-xl text-gray-900 dark:text-white focus:bg-white dark:focus:bg-gray-600 focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20 transition-all duration-200"
            >
              <option value="">Sin categoría</option>
              <option v-for="cat in taskCategories" :key="cat.name" :value="cat.name">
                {{ cat.icon }} {{ cat.name }}
              </option>
            </select>
          </div>

          <div>
            <label class="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
              <Hash class="h-4 w-4 inline mr-1" />
              Etiquetas
            </label>
            <div class="flex flex-wrap gap-2 mb-2">
              <span
                v-for="tag in form.tags"
                :key="tag"
                class="px-3 py-1 bg-blue-100 dark:bg-blue-900 text-blue-600 dark:text-blue-400 rounded-full text-sm"
              >
                {{ tag }}
                <button @click="removeTag(tag)" class="ml-1 hover:text-blue-800">
                  <Trash2 class="h-3 w-3 inline" />
                </button>
              </span>
            </div>
            <div class="flex space-x-2">
              <input
                v-model="newTag"
                type="text"
                @keyup.enter="addTag"
                class="flex-1 px-4 py-2 bg-gray-100 dark:bg-gray-700 border border-transparent rounded-xl text-gray-900 dark:text-white placeholder-gray-500 dark:placeholder-gray-400 focus:bg-white dark:focus:bg-gray-600 focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20 transition-all duration-200"
                placeholder="Agregar etiqueta..."
              />
              <button
                @click="addTag"
                class="px-4 py-2 bg-gray-200 dark:bg-gray-600 text-gray-700 dark:text-gray-300 rounded-xl hover:bg-gray-300 dark:hover:bg-gray-500 transition-all"
              >
                <Plus class="h-5 w-5" />
              </button>
            </div>
          </div>
        </div>

        <!-- Attachments Tab -->
        <div v-else-if="activeTab === 'attachments'" class="space-y-4">
          <div class="border-2 border-dashed border-gray-300 dark:border-gray-600 rounded-xl p-8 text-center">
            <Paperclip class="h-12 w-12 text-gray-400 mx-auto mb-4" />
            <p class="text-gray-500 dark:text-gray-400 mb-2">
              Arrastra archivos aquí o haz clic para subir
            </p>
            <p class="text-sm text-gray-400 dark:text-gray-500">
              Soporta: PDF, imágenes, documentos (max 10MB)
            </p>
          </div>
        </div>

        <!-- Activity Tab -->
        <div v-else class="space-y-4 max-h-64 overflow-y-auto">
          <div
            v-for="item in activity"
            :key="item.id"
            class="flex items-start space-x-3 p-3 bg-gray-50 dark:bg-gray-700 rounded-xl"
          >
            <div class="w-8 h-8 bg-gradient-to-r from-blue-500 to-purple-500 rounded-full flex items-center justify-center text-white text-sm font-medium flex-shrink-0">
              {{ item.user_name.charAt(0) }}
            </div>
            <div class="flex-1">
              <p class="text-sm font-medium text-gray-900 dark:text-white">
                {{ item.action }}
              </p>
              <p class="text-sm text-gray-500 dark:text-gray-400">
                {{ item.details }}
              </p>
              <p class="text-xs text-gray-400 dark:text-gray-500 mt-1">
                {{ formatDate(item.created_at) }}
              </p>
            </div>
          </div>
        </div>
      </div>

      <!-- Footer -->
      <div class="flex items-center justify-end space-x-3 p-6 border-t border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-800/50">
        <button
          type="button"
          @click="emit('close')"
          class="px-6 py-2.5 bg-gray-200 dark:bg-gray-700 text-gray-700 dark:text-gray-300 rounded-xl font-medium hover:bg-gray-300 dark:hover:bg-gray-600 transition-all"
        >
          Cancelar
        </button>
        <button
          @click="handleSubmit"
          class="px-6 py-2.5 bg-gradient-to-r from-blue-600 to-purple-600 text-white rounded-xl font-medium hover:from-blue-700 hover:to-purple-700 transition-all flex items-center space-x-2"
        >
          <Sparkles class="h-5 w-5" />
          <span>{{ task ? 'Guardar Cambios' : 'Crear Tarea' }}</span>
        </button>
      </div>
    </div>
  </div>
</template>
