// taskflow-app-vue/src/components/TaskCard.vue
<script setup lang="ts">
import { Clock, Star, Trash2, Edit, Check } from 'lucide-vue-next';
import type { Task } from '@/types';

const props = defineProps<{
  task: Task;
}>();

const emit = defineEmits(['toggle', 'edit', 'delete', 'favorite']);

const priorityColors = {
  low: 'bg-gray-100 text-gray-600 dark:bg-gray-700 dark:text-gray-300',
  medium: 'bg-yellow-100 text-yellow-600 dark:bg-yellow-900 dark:text-yellow-300',
  high: 'bg-red-100 text-red-600 dark:bg-red-900 dark:text-red-300'
};

const priorityLabels = {
  low: 'Baja',
  medium: 'Media',
  high: 'Alta'
};
</script>

<template>
  <div
    :class="[
      'p-4 bg-white dark:bg-gray-800 rounded-xl shadow-sm border border-gray-200 dark:border-gray-700 hover:shadow-md transition-all cursor-pointer',
      task.completed && 'opacity-60'
    ]"
    @click="emit('edit', task)"
  >
    <div class="flex items-start space-x-4">
      <!-- Checkbox -->
      <button
        @click.stop="emit('toggle')"
        :class="[
          'mt-1 w-6 h-6 rounded-lg border-2 flex items-center justify-center transition-all flex-shrink-0',
          task.completed
            ? 'bg-green-500 border-green-500 text-white'
            : 'border-gray-300 dark:border-gray-600 hover:border-blue-500'
        ]"
      >
        <Check v-if="task.completed" class="h-4 w-4" />
      </button>

      <!-- Content -->
      <div class="flex-1 min-w-0">
        <div class="flex items-center space-x-2 mb-1 flex-wrap">
          <h3
            :class="[
              'font-medium text-gray-900 dark:text-white',
              task.completed && 'line-through text-gray-500'
            ]"
          >
            {{ task.title }}
          </h3>
          <span
            v-if="task.priority"
            :class="['px-2 py-0.5 rounded-full text-xs font-medium', priorityColors[task.priority]]"
          >
            {{ priorityLabels[task.priority] }}
          </span>
        </div>
        <p v-if="task.description" class="text-sm text-gray-500 dark:text-gray-400 truncate">
          {{ task.description }}
        </p>
        <div class="flex items-center space-x-4 mt-2 text-sm text-gray-400">
          <span v-if="task.dueDate" class="flex items-center space-x-1">
            <Clock class="h-4 w-4" />
            <span>{{ task.dueDate }}</span>
          </span>
        </div>
      </div>

      <!-- Actions -->
      <div class="flex items-center space-x-1 flex-shrink-0">
        <button
          @click.stop="emit('favorite')"
          :class="['p-2 rounded-lg transition-all', task.favorite ? 'text-yellow-500' : 'text-gray-400 hover:text-yellow-500']"
        >
          <Star class="h-5 w-5" :fill="task.favorite ? 'currentColor' : 'none'" />
        </button>
        <button
          @click.stop="emit('edit', task)"
          class="p-2 text-gray-400 hover:text-blue-500 rounded-lg transition-all"
        >
          <Edit class="h-5 w-5" />
        </button>
        <button
          @click.stop="emit('delete')"
          class="p-2 text-gray-400 hover:text-red-500 rounded-lg transition-all"
        >
          <Trash2 class="h-5 w-5" />
        </button>
      </div>
    </div>
  </div>
</template>

// taskflow-app-main/src/components/Tasks/TaskCard.tsx
import { CheckCircle, Circle, Calendar, Trash2, Edit, Users, Share2, Tag, AlertTriangle, Clock } from 'lucide-react';
import { Task } from '../../types/database';

const getTagsArray = (tags: string | string[] | undefined): string[] => {
  if (!tags) return [];
  if (Array.isArray(tags)) return tags;
  return tags.split(',').filter(t => t.trim());
};

interface TaskCardProps {
  task: Task;
  onToggleStatus: (id: number) => void;
  onDelete: (id: number) => void;
  onEdit: (task: Task) => void;
  onShare?: (task: Task) => void;
  isShared?: boolean;
  userPermission?: 'owner' | 'view' | 'edit' | 'admin';
}

const TaskCard: React.FC<TaskCardProps> = ({ 
  task, 
  onToggleStatus, 
  onDelete, 
  onEdit, 
  onShare,
  isShared = false,
  userPermission = 'owner'
}) => {
  const formatDate = (dateString: string) => {
    const date = new Date(dateString);
    return new Intl.DateTimeFormat('es-ES', {
      day: 'numeric',
      month: 'short',
      year: 'numeric'
    }).format(date);
  };

  const getPriorityColor = (priority?: string) => {
    switch (priority) {
      case 'high': return 'text-red-600 bg-red-100';
      case 'medium': return 'text-yellow-600 bg-yellow-100';
      case 'low': return 'text-green-600 bg-green-100';
      default: return 'text-gray-600 bg-gray-100';
    }
  };

  const getPriorityIcon = (priority?: string) => {
    switch (priority) {
      case 'high': return <AlertTriangle className="h-3 w-3" />;
      case 'medium': return <Clock className="h-3 w-3" />;
      case 'low': return <Circle className="h-3 w-3" />;
      default: return null;
    }
  };

  const isOverdue = task.due_date && new Date(task.due_date) < new Date() && !task.completed;
  
  const canEdit = userPermission === 'owner' || userPermission === 'edit' || userPermission === 'admin';
  const canDelete = userPermission === 'owner';
  const canShare = userPermission === 'owner';

  return (
    <div className={`bg-white dark:bg-gray-800 rounded-lg shadow-sm border-2 transition-all duration-200 hover:shadow-md ${
      task.completed ? 'border-green-200 dark:border-green-800 bg-green-50 dark:bg-green-900/20' : 'border-gray-200 dark:border-gray-700'
    }`}>
      <div className="p-4 md:p-6">
        <div className="flex items-start justify-between">
          <div className="flex items-start space-x-3 flex-1">
            <button
              onClick={() => onToggleStatus(task.id)}
              className={`mt-1 transition-colors ${
                task.completed 
                  ? 'text-green-600 hover:text-green-700' 
                  : 'text-gray-400 hover:text-gray-600'
              }`}
            >
              {task.completed ? (
                <CheckCircle className="h-5 w-5" />
              ) : (
                <Circle className="h-5 w-5" />
              )}
            </button>
            
            <div className="flex-1 min-w-0">
              <h3 className={`text-base md:text-lg font-semibold ${
                task.completed 
                  ? 'line-through text-gray-500 dark:text-gray-400' 
                  : 'text-gray-900 dark:text-white'
              } break-words truncate`}>
                {task.title}
              </h3>
              
              <p className={`mt-1 text-sm ${
                task.completed 
                  ? 'text-gray-400 dark:text-gray-500' 
                  : 'text-gray-600 dark:text-gray-300'
              } break-words truncate`}>
                {task.description || 'Sin descripción'}
              </p>

              {/* Category */}
              {task.category && (
                <div className="mt-2">
                  <span className="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-blue-100 text-blue-800">
                    {task.category}
                  </span>
                </div>
              )}

              {/* Tags */}
              {(() => {
                const tagsArray = getTagsArray(task.tags);
                return tagsArray.length > 0 ? (
                  <div className="flex flex-wrap gap-1 mt-2">
                    {tagsArray.map((tag, index) => (
                      <span
                        key={index}
                        className="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-gray-100 text-gray-800"
                      >
                        <Tag className="h-3 w-3 mr-1" />
                        {tag}
                      </span>
                    ))}
                  </div>
                ) : null;
              })()}

              {/* Priority and Due Date */}
              <div className="flex items-center justify-between mt-3 flex-wrap gap-2">
                <div className="flex items-center space-x-2">
                  <div className="flex items-center text-xs text-gray-500">
                    <Calendar className="h-4 w-4 mr-1" />
                    {formatDate(task.created_at)}
                  </div>
                  
                  {task.priority && (
                    <span className={`inline-flex items-center px-2 py-1 rounded-full text-xs font-medium ${getPriorityColor(task.priority)}`}>
                      {getPriorityIcon(task.priority)}
                      <span className="ml-1 capitalize">{task.priority}</span>
                    </span>
                  )}
                </div>

                <div className="flex items-center space-x-2">
                  {task.due_date && (
                    <div className={`flex items-center text-xs ${isOverdue ? 'text-red-600 font-medium' : 'text-gray-500'}`}>
                      <Clock className="h-3 w-3 mr-1" />
                      {formatDate(task.due_date)}
                      {isOverdue && ' (Vencida)'}
                    </div>
                  )}
                  
                  {isShared && (
                    <div className="flex items-center text-xs text-blue-600">
                      <Users className="h-3 w-3 mr-1" />
                      Compartida
                    </div>
                  )}
                </div>
              </div>
            </div>
          </div>
          
          <div className="flex items-center space-x-2 ml-4">
            {canShare && onShare && (
              <button
                onClick={() => onShare(task)}
                className="text-gray-400 hover:text-green-600 transition-colors"
                title="Compartir tarea"
              >
                <Share2 className="h-4 w-4" />
              </button>
            )}
            
            {canEdit && (
              <button
                onClick={() => onEdit(task)}
                className="text-gray-400 hover:text-blue-600 transition-colors"
                title="Editar tarea"
              >
                <Edit className="h-4 w-4" />
              </button>
            )}
            
            {canDelete && (
              <button
                onClick={() => onDelete(task.id)}
                className="text-gray-400 hover:text-red-600 transition-colors"
                title="Eliminar tarea"
              >
                <Trash2 className="h-4 w-4" />
              </button>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};

export default TaskCard;
